<h1>Kontakty</h1>
<div class="cont">
	<table class="cont_tab">
		<tr>
			<td>
				<p><u>Jednatel</u><br/>
					Přemysl Himlar<br/>
					Mobil: +420 777 715 545<br/>
					Email: <a href="mailto:hidem@hidem.cz">hidem@hidem.cz</a>
				</p><br/><br/>
			</td>
		</tr>

		<tr>
			<td>
				<p><u>Sekretariát</u><br/>
					Telefon: 596 415 551<br/>
					Mobil: +420 777 715 550<br/>
					Email: <a href="mailto:info@hidem.cz">info@hidem.cz</a><br/>
					Fax: 596 415 552
				</p>
			</td>
		</tr>
	</table>

	<p style="color: red;">Nové sídlo od 1. 1. 2014</p>
	<iframe src="https://mapsengine.google.com/map/embed?mid=zVoCvwZiaDzw.k0RcxRJF4OZI" width="640"
			height="480"></iframe>


</div>
