<h1>Užitečné odkazy</h1>
<a href="http://www.obchodnirejstrik.cz" target="_blank">Obchodní rejstřík</a><br /><br />
<a href="http://wwwinfo.mfcr.cz" target="_blank">ARES - registr ekonomických subjektů</a><br /> <br />
<a href="http://adisreg.mfcr.cz" target="_blank">Registr plátců DPH</a><br /> <br />
<a href="http://www.cnb.cz" target="_blank">Aktuální kurz ČNB</a><br /> <br />
<a href="http://www.mfcr.cz" target="_blank">Ministerstvo financí ČR</a><br /> <br />
<a href="http://www.mpsv.cz" target="_blank">Ministerstvo práce a sociálních věcí ČR</a><br /> <br />
<a href="http://www.justice.cz" target="_blank">Justice ČR</a><br /> <br />
<a href="http://cds.mfcr.cz" target="_blank">Daňová správa</a><br /> <br />
<a href="http://adisepo.mfcr.cz" target="_blank">Daňový portál</a><br /> <br />
<a href="http://nahlizenidokn.cuzk.cz" target="_blank">Katastr nemovitostí</a><br /> <br />
<a href="http://www.businessinfo.cz/cs/clanky/danovy-kalendar-pro-rok-2015-59523.html" target="_blank">Daňový kalendář 2015</a>