<h1>Kde nás najdete?</h1>
	<p class="left">je to úplně jednoduché, nacházíme se na adrese Lidická 1261/43c Havířov-Šumbark.</p>

	<a href="http://go.mapa.cz/planovat-trasu-autem-m38?p[20]=49.79713279427805,18.401745557785034" target="_blank">
		GPS souřadnice
	</a><br /><br />

	<iframe src="https://mapsengine.google.com/map/embed?mid=zVoCvwZiaDzw.k0RcxRJF4OZI" width="640"	height="480">

	</iframe>
