<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<base href="/localhost"/>
	<meta name="description" content="HiDEM s.r.o."/>
	<meta name="keywords" content="daňe, dane, účetnictví, ucetnictvi, mzdy, Havířov, Havirov"/>
	<meta name="googlebot" content="snippet,archive"/>

	<title><?php echo $titulek; ?> - HiDEM s.r.o.</title>

	<link rel="stylesheet" href="style.css" type="text/css"/>

</head>

<body>
<header>
	<p></p>
</header>
<nav>
	
        <span class="citac">Počítadlo: 
            <!-- BlueBoard.cz Pocitadlo -->
              <span id="bbpocitadlo-span-ejf84c9eepj22hfn03047emfih2pun"><a
					  id="bbpocitadlo-ejf84c9eepj22hfn03047emfih2pun"
					  href="http://miniaplikace.blueboard.cz"></a></span>
              <script type="text/javascript"
					  src="http://miniaplikace.blueboard.cz/counter_1.php?jid=ejf84c9eepj22hfn03047emfih2pun"></script>
            <!-- BlueBoard.cz Pocitadlo KONEC -->
        </span>

	<a <?php if ($url === 'uvod') echo 'class="menu_active"'; else echo 'class="menu_a"'; ?> href="../uvod">HLAVNÍ
		STRÁNKA</a>
	<a <?php if ($url === 'dane') echo 'class="menu_active"'; else echo 'class="menu_a"'; ?> href="../dane">DANĚ</a>
	<a <?php if ($url === 'ucetnictvi') echo 'class="menu_active"'; else echo 'class="menu_a"'; ?> href="../ucetnictvi">ÚČETNICTVÍ</a>
	<a <?php if ($url === 'mzdy') echo 'class="menu_active"'; else echo 'class="menu_a"'; ?> href="../mzdy">MZDY</a>
	<a <?php if ($url === 'provize') echo 'class="menu_active"'; else echo 'class="menu_a"'; ?> href="../provize">PROVIZE</a>
	<a <?php if ($url === 'odkazy') echo 'class="menu_active"'; else echo 'class="menu_a"'; ?>
		href="../odkazy">ODKAZY</a>
	<a <?php if ($url === 'poloha') echo 'class="menu_active"'; else echo 'class="menu_a"'; ?> href="../poloha">MAPA</a>

</nav>
<section>

	<div class="obsah1"></div>
	<div class="obsah2">
		<?php
		$zprava = '<strong>Upozornění</strong><br />Ode dne 29. 6. do 3. 7. 2015 bude účetní kancelář z důvodu firemní dovolené uzavřena.<br /> Děkujeme za pochopení.';

		$message = $this->kontroler->flashMessage(new DateTime("2015-7-3"), $zprava);

		if ($message)
			echo $message;

		$this->kontroler->vypisPohled(); // vložení aktuálního pohledu do šablony
		?>
	</div>
	<div class="obsah3">
		<ul class="cont">
			<li>
				<p><u>Jednatel</u><br />
					Přemysl Himlar<br />
					+420 777 715 545<br />
					<a href="mailto:hidem@hidem.cz">hidem@hidem.cz</a>
				</p>
			</li>

			<li>
				<p><u>Sekretariát</u><br />
					596 415 551<br />
					+420 777 715 550<br />
					<a href="mailto:info@hidem.cz">info@hidem.cz</a><br />
					Fax: 596 415 552
				</p>
			</li>

			<li>
				<p><u>Adresa:</u><br />
					Lidická 43c<br />
					Havířov - Šumbark<br />
					736 01<br /><br />
					IČ: 25285891<br />
					DIČ: CZ25285891<br />
				</p>
			</li>
		</ul>

		<hr>

		<div id="blok-bbsluzba-jnbenx6ipcduiovxh7v0jue3o8eatx"></div>

		<a id="odkaz-bbsluzba-jnbenx6ipcduiovxh7v0jue3o8eatx" href="http://miniaplikace.blueboard.cz">Miniaplikace</a>

		<script type="text/javascript"
				src="http://miniaplikace.blueboard.cz/widget-pocasi-jnbenx6ipcduiovxh7v0jue3o8eatx"></script>

		<br style="clear: both;"/>

	</div>
	<br style="clear: both;"/>

</section>
<footer>
	<p>Vytvořil Martin Himlar pro HiDEM s.r.o.</p>
</footer>
<script>
	(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
			(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

	ga('create', 'UA-77928659-1', 'auto');
	ga('send', 'pageview');

</script>
</body>
</html>
