<h1>Účetnictví</h1>
<p>
    &nbsp;&nbsp;V podvojném účetnictví zpracujeme, zkontrolujeme a připravíme veškeré doklady a podklady týkající se podnikání. Připravíme přiznání k DPH. Dále zpracujeme rozvahu, výkazy zisků a ztrát, případně další přehledy. Připravíme také statistické výkazy. 
    <br />&nbsp;&nbsp;Vedení účetnictví zahrnuje také evidenci hmotného a nehmotného majetku. K evidenci majetku neodmyslitelně patří zpracování daňových a účetních odpisů. Jsme schopni pro klienta vést i skladovou evidenci včetně vystavování vydaných faktur. Součástí vedení účetnictví je i kontrola saldokontních účtů. Saldokontní účty slouží pro přesné sledování závazků, pohledávek, jejich splatnosti a plateb. Důležitou součástí vedení účetnictví je účetní závěrka, která se provádí na konci každého účetního období. Případně i v mimořádných termínech. Závěrku zpracujeme dle zákonných požadavků, provedeme digitalizaci a uložení potřebných dokumentů k archivaci na příslušném rejstříku.
    <br />&nbsp;&nbsp;Současně s vedením podvojného účetnictví Vám dále nabízíme daňové poradenství, mzdy a personalistiku včetně ekonomického poradenství.
</p>


<h1 class="nadpisy">Daňová evidence</h1>

<p>
    &nbsp;&nbsp;Nabízíme Vám vedení daňové evidence. Ušetříme Vám čas a poskytneme informace o prosperitě Vaší firmy. Zpracujeme, zkontrolujeme a připravíme veškeré doklady a podklady týkající se Vašeho podnikání. Připravíme Vám přiznání k DPH. Vedení daňové evidence zahrnuje také evidenci hmotného a nehmotného majetku. K evidenci majetku neodmyslitelně patří zpracování daňových a účetních odpisů. Provedeme kontrolu pohledávek a závazků. Jsme schopni pro klienta vést i skladovou evidenci včetně vystavování vydaných faktur. Dále nabízíme daňové poradenství, mzdy a personalistiku, ekonomické poradenství a možnost převést podnikání z fyzické osoby na s.r.o.
    <br />&nbsp;&nbsp;Základ pro výpočet daně z příjmů zjistíme z daňové evidence porovnáním daňových příjmů a výdajů. Připravíme veškeré podklady potřebné pro výpočet daně z příjmů.
    <br />&nbsp;&nbsp;Dále nabízíme zpracování ročních výkazů pro sociální správu a zdravotní pojišťovny a přípravu k tomu všech potřebných podkladů.
</p>
