<p>
&nbsp;&nbsp;Na trhu působíme více než dvacet let, a to zejména v oblastech Ostravska, Opavska a Karvinska.
	Neustále pracujeme na zdokonalování našich služeb.
	Z původní fyzické osoby jsme se transformovali v roce 2006 na právnickou osobu HiDEM s.r.o.<br /><br />
&nbsp;&nbsp;Nabízíme komplexní daňové a účetní služby, a to v oblastech vedení účetnictví a daňové evidence,
	zpracování mzdové agendy a generálního zastupování na všech institucích týkajících se podnikání.
	Našim cílem je nalézt pro klienty optimální řešení pro jejich podnikání.
	Proto klademe důraz nejen na osobní přístup, ale také na odbornost a kvalifikaci našich zaměstnanců.<br /><br />
   
&nbsp;&nbsp;Využitím našich služeb ušetříte nejen čas, ale i náklady vzhledem k neustále se měnícím zákonům,
	zpracování účetnictví, mezd a aktualizací softwaru.
	<br /><br />

Rádi bychom pomohli i Vám. Těšíme se na spolupráci s Vámi.<br /><br />
                                                
Přemysl Himlar, jednatel společnosti<br />
HiDEM s.r.o., Účetní kancelář
</p>